// <auto-generated />
namespace Background.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190510 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190510));
        
        string IMigrationMetadata.Id
        {
            get { return "201905100732183_20190510"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
